"""Implement leaves.

Revision ID: edd78028a980
Revises: f3c9279437f4
Create Date: 2025-05-13 19:57:03.945668

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edd78028a980"
down_revision: str | None = "f3c9279437f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters_arrays",
        sa.Column("cluster_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "full_paths", postgresql.ARRAY(sa.BIGINT(), dimensions=2), nullable=False
        ),
        sa.Column("leaf_cluster_ids", postgresql.ARRAY(sa.BIGINT()), nullable=False),
        sa.PrimaryKeyConstraint("cluster_id"),
        schema="mb",
    )
    op.create_table(
        "clusters_leaves",
        sa.Column("cluster_leaf_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", sa.BIGINT(), nullable=False),
        sa.Column("leaf_cluster_id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("cluster_leaf_id"),
        schema="mb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clusters_leaves", schema="mb")
    op.drop_table("clusters_arrays", schema="mb")
    # ### end Alembic commands ###
