import warnings
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict

from pandas import DataFrame
from pydantic import BaseModel, Field, ValidationInfo, field_validator

from matchbox.data.results import ProbabilityResults


class DeduperSettings(BaseModel):
    """
    A data class to enforce basic settings dictionary shapes
    """

    id: str = Field(description="A unique ID column in the table to dedupe")

    @field_validator("id")
    @classmethod
    def _id_for_cmf(cls, v: str, info: ValidationInfo) -> str:
        enforce = "data_sha1"
        if v != enforce:
            warnings.warn(
                f"For offline deduplication, {info.field_name} can be any field. \n\n"
                "When deduplicating to write back to the Company Matching "
                f"Framework database, the ID must be {enforce}, generated by "
                "retrieving data with cmf.query()."
            )
        return v


class Deduper(BaseModel, ABC):
    settings: DeduperSettings

    @classmethod
    @abstractmethod
    def from_settings(cls) -> "Deduper":
        raise NotImplementedError(
            """\
            Must implement method to instantiate from settings \
            -- consider creating a pydantic model to enforce shape.
        """
        )

    @abstractmethod
    def prepare(self, data: DataFrame) -> None:
        return

    @abstractmethod
    def dedupe(self, data: DataFrame) -> DataFrame:
        return


def make_deduper(
    dedupe_run_name: str,
    description: str,
    deduper: Deduper,
    deduper_settings: Dict[str, Any],
    data: DataFrame,
    data_source: str,
) -> Callable[[DataFrame], ProbabilityResults]:
    deduper_instance = deduper.from_settings(**deduper_settings)
    deduper_instance.prepare(data)

    def deduper(data: DataFrame = data) -> ProbabilityResults:
        return ProbabilityResults(
            dataframe=deduper_instance.dedupe(data=data),
            run_name=dedupe_run_name,
            description=description,
            left=data_source,
            right=data_source,
        )

    return deduper
