from uuid import UUID, uuid4

from sqlalchemy import func
from sqlalchemy.orm import Mapped, mapped_column


class SHA1Mixin:
    # Not autogenerated
    sha1: Mapped[bytes] = mapped_column(primary_key=True)


class UUIDMixin:
    uuid: Mapped[UUID] = mapped_column(
        primary_key=True, default=uuid4, server_default=func.gen_random_uuid()
    )
